name: agner

language: GHC2021

default-extensions:
  - LambdaCase
  - CPP
  - OverloadedLabels
  - DerivingStrategies
  - DeriveAnyClass
  - BlockArguments
  - OverloadedRecordDot
  - StrictData
  - AllowAmbiguousTypes
  - RecursiveDo
  - ImplicitParams
  - DataKinds
  - DuplicateRecordFields
  - PatternSynonyms
  - OverloadedStrings
  - ViewPatterns
  - GeneralizedNewtypeDeriving
  - NoFieldSelectors
  - PartialTypeSignatures

ghc-options:
  - -Wincomplete-patterns
  - -Wno-partial-type-signatures

dependencies:
  - base

extra-source-files:
  - runtime/tags.h

data-files:
  - runtime/*.c
  - runtime/*.h

library:
  source-dirs: src
  dependencies:
    - ghc-prim

    - containers

    - mtl
    - transformers
    - lens
    - generic-lens

    - megaparsec
    - parser-combinators

executables:
  agner:
    main: Main.hs
    dependencies:
      - agner
      - typed-process
      - filepath
      - named
