name: agner

default-extensions:
  - LambdaCase
  - CPP
  - OverloadedLabels
  - DerivingStrategies
  - DeriveAnyClass
  - DeriveGeneric
  - EmptyDataDeriving
  - BlockArguments
  - ImportQualifiedPost
  - OverloadedRecordDot
  - StrictData
  - ScopedTypeVariables
  - NamedFieldPuns
  - BangPatterns
  - FlexibleContexts
  - TypeApplications
  - AllowAmbiguousTypes
  - BinaryLiterals
  - RecursiveDo
  - ImplicitParams
  - ConstraintKinds
  - TypeOperators
  - DataKinds
  - OverloadedLabels
  - DuplicateRecordFields

ghc-options:
  - -Wincomplete-patterns

dependencies:
  - base
  - aeson

extra-source-files:
  - src/Language/Agner/X64.h

library:
  source-dirs: src
  dependencies:
    - containers

    - mtl
    - lens
    - generic-lens

    - megaparsec
    - parser-combinators

executables:
  agner:
    main: Main.hs
    source-dirs: app
    dependencies:
      - agner
      - typed-process
      - temporary
      - filepath
      - named
