name: agner

default-extensions:
  - LambdaCase
  - CPP
  - OverloadedLabels
  - DerivingStrategies
  - DeriveAnyClass
  - DeriveGeneric
  - EmptyDataDeriving
  - BlockArguments
  - ImportQualifiedPost
  - OverloadedRecordDot
  - StrictData
  - ScopedTypeVariables
  - NamedFieldPuns
  - BangPatterns
  - FlexibleContexts
  - TypeApplications
  - AllowAmbiguousTypes
  - BinaryLiterals
  - RecursiveDo
  - ImplicitParams
  - ConstraintKinds
  - TypeOperators
  - DataKinds
  - OverloadedLabels
  - DuplicateRecordFields
  - GADTs
  - PatternSynonyms
  - OverloadedStrings
  - RankNTypes
  - ViewPatterns
  - GeneralizedNewtypeDeriving
  - NoFieldSelectors

ghc-options:
  - -Wincomplete-patterns

dependencies:
  - base
  - aeson

extra-source-files:
  - src/Language/Agner/X64.h

library:
  source-dirs: src
  dependencies:
    - ghc-prim

    - containers

    - mtl
    - transformers
    - lens
    - generic-lens
    - free

    - megaparsec
    - parser-combinators

    - unicode-show
    - prettyprinter
    - prettyprinter-ansi-terminal

executables:
  agner:
    main: Main.hs
    source-dirs: app
    dependencies:
      - agner
      - typed-process
      - temporary
      - filepath
      - named
