#!/usr/bin/env bash

clear

tmp_dir=$(mktemp -d)
tmp_file="$tmp_dir/main.c"
echo "int main() {}" > $tmp_file
trap "rm -rf $tmp_dir" 0 2 3 15

gcc heap.c list.c mailbox.c options.c process.c runtime.c scheduler.c throw.c value.c $tmp_file -o /dev/null
